"""

SUPPLEMENTARY FIGURE — XAI INPUT CORRELATION

================================================================



Final temporal-safe, strict-OOF run

-------------------------

/athena/madelab/scratch/iqh4001/VitalDB/Inspire/Results/

darn_cv_baseline_runs/v6_temporal_safe_strict_oof_parallel/run_20260919_115653



Panels

------

A. Cluster-ordered Spearman correlation among the top directly attributed

   Uniform DARN features.

B. Horizontal hierarchical clustering of the same features.

C. Spearman correlation among clinical-domain input summaries.

D. Direct Uniform DARN GradientSHAP attribution aggregated by clinical domain.



Current-run methodology

-----------------------

The strict-OOF model uses five fold-specific preprocessing pipelines and

five fold-specific selected feature sets. This script therefore:



1. Reconstructs the ASA-6-excluded cohort and exact saved holdout order.

2. Loads every current-run fold-specific preprocessor, variance selector,

   selected feature list, and domain map.

3. Aligns transformed features by name across folds.

4. Averages transformed feature values across folds in which each feature was

   selected.

5. Ranks features using the strict-OOF direct GradientSHAP importance table

   generated from the saved Uniform DARN models.

6. Computes correlations on the complete held-out test cohort rather than the

   event-enriched attribution subset.



The figure describes correlation and clustering of model inputs. It does not

imply causal relationships, and fixed uniform DARN domain weights are not

interpreted as learned importance.



Required current-run inputs

---------------------------

- config.json

- test_predictions_all_models.csv

- fold_artifacts/fold_1 ... fold_5

- strict-OOF direct Uniform DARN feature-importance CSV generated by Figure 4



Run in Jupyter

--------------

%run FigureS_current_v6_XAI_input_correlation_2x2.py

"""



from __future__ import annotations



import argparse

import importlib.util

import json

import pathlib

import re

import sys

import warnings

from collections import Counter, defaultdict

from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple



import joblib

import matplotlib as mpl

import matplotlib.pyplot as plt

import numpy as np

import pandas as pd

from matplotlib import cm

from scipy.cluster.hierarchy import dendrogram, linkage

from scipy.spatial.distance import squareform



warnings.filterwarnings("ignore")





# =============================================================================

# DEFAULT CURRENT-RUN SETTINGS

# =============================================================================



DEFAULT_RUN_DIR = pathlib.Path(

    "/athena/madelab/scratch/iqh4001/VitalDB/Inspire/Results/"

    "darn_cv_baseline_runs/v6_temporal_safe_strict_oof_parallel/run_20260919_115653"

)



DEFAULT_PIPELINE_MODULE = pathlib.Path(

    "/athena/madelab/scratch/iqh4001/VitalDB/Inspire/Code/New/"

    "Mortality_DARN_full_pipe_v6_temporal_safe_strict_oof.py"

)



DEFAULT_DATA_PATH = pathlib.Path(

    "/athena/madelab/scratch/iqh4001/VitalDB/Inspire/Results/"

    "Final_Datasets/df_final_mortality_2026-05-24_12-44_temporal_safe.csv"

)



DEFAULT_OUTPUT_SUBDIR = (

    "figures_revised_manuscript/"

    "supplementary_xai_input_correlation_strict_oof"

)



FIGURE_BASENAME = "FigS_TemporalSafe_StrictOOF_XAI_Input_Correlation_2x2"



TOP_K = 25

CORRELATION_CMAP = "coolwarm"

ATTRIBUTION_CMAP = "plasma"

CLUSTER_LINKAGE_METHOD = "average"



DOMAIN_DISPLAY_MAP: Dict[str, str] = {

    "Demographics": "Demographics",

    "Diagnoses": "Diagnoses",

    "Durations": "Durations",

    "Interactions": "Interactions",

    "Emergency_Interactions": "Interactions",

    "Intraop_Vitals": "Intraoperative variables",

    "Medications": "Medications",

    "Preop_Labs": "Preoperative laboratories",

    "Procedures": "Procedures",

    "Other": "Other",

}



DOMAIN_CANONICAL_MAP: Dict[str, str] = {

    "Emergency_Interactions": "Interactions",

    "Emergency interactions": "Interactions",

    "Preoperative laboratories": "Preop_Labs",

    "Intraoperative vitals": "Intraop_Vitals",

    "Intraoperative variables": "Intraop_Vitals",

}





# =============================================================================

# GENERAL HELPERS

# =============================================================================



def require_file(path: pathlib.Path) -> pathlib.Path:

    if not path.exists():

        raise FileNotFoundError(

            f"\nRequired current-run artifact not found:\n{path}\n"

            "Confirm the run directory and file paths."

        )

    return path





def first_existing(

    candidates: Iterable[pathlib.Path],

    description: str,

) -> pathlib.Path:

    checked: List[pathlib.Path] = []



    for path in candidates:

        checked.append(path)

        if path.exists():

            return path



    checked_text = "\n".join(f"  - {path}" for path in checked)

    raise FileNotFoundError(

        f"Could not locate {description}. Checked:\n{checked_text}"

    )





def load_json(path: pathlib.Path) -> Dict[str, Any]:

    with open(require_file(path), "r", encoding="utf-8") as handle:

        return json.load(handle)





def save_json(data: Mapping[str, Any], path: pathlib.Path) -> None:

    def convert(value: Any) -> Any:

        if isinstance(value, pathlib.Path):

            return str(value)

        if isinstance(value, np.ndarray):

            return value.tolist()

        if isinstance(value, (np.integer,)):

            return int(value)

        if isinstance(value, (np.floating,)):

            return float(value)

        raise TypeError(f"Cannot serialize {type(value)}")



    with open(path, "w", encoding="utf-8") as handle:

        json.dump(data, handle, indent=2, default=convert)





def load_pipeline_module(module_path: pathlib.Path):

    require_file(module_path)



    spec = importlib.util.spec_from_file_location(

        "mortality_darn_v6_correlation_module",

        module_path,

    )



    if spec is None or spec.loader is None:

        raise ImportError(

            f"Could not import pipeline module: {module_path}"

        )



    module = importlib.util.module_from_spec(spec)

    sys.modules[spec.name] = module

    spec.loader.exec_module(module)

    return module





def normalize_object_array(values: np.ndarray) -> np.ndarray:

    return np.asarray(values, dtype=object).astype(str)





def canonical_domain(domain: Any) -> str:

    raw = str(domain).strip()

    return DOMAIN_CANONICAL_MAP.get(raw, raw)





def display_domain(domain: Any) -> str:

    canonical = canonical_domain(domain)

    return DOMAIN_DISPLAY_MAP.get(

        canonical,

        canonical.replace("_", " "),

    )





def compress_words(

    text: str,

    front: int = 4,

    back: int = 2,

) -> str:

    words = str(text).split()



    if len(words) <= front + back + 1:

        return str(text)



    return (

        " ".join(words[:front])

        + " … "

        + " ".join(words[-back:])

    )





# =============================================================================

# SHORT, TIDY FEATURE LABELS

# =============================================================================



SHORT_LABEL_MAP = {

    "age": "Age",

    "sex": "Sex",

    "race": "Race",

    "bmi": "BMI",

    "asa": "ASA class",

    "emop": "Emergency surgery",

    "or_duration": "OR duration",

    "surgery_duration": "Surgery duration",

    "anesthesia_duration": "Anesthesia duration",



    "int_age_x_emergency": "Age × emergency surgery",

    "int_asa_x_emergency": "ASA × emergency surgery",

    "int_emergency_x_or_duration": "Emergency × OR duration",

    "int_emergency_x_surgery_duration": "Emergency × surgery duration",

    "int_emergency_x_anesthesia_duration": "Emergency × anesthesia duration",



    "preop_fibrinogen": "Preop fibrinogen",

    "preop_platelet": "Preop platelets",

    "preop_alp": "Preop alkaline phosphatase",

    "preop_glucose": "Preop glucose",

    "preop_lymphocyte": "Preop lymphocytes",

    "preop_ast": "Preop AST",

    "preop_alt": "Preop ALT",

    "preop_albumin": "Preop albumin",

    "preop_creatinine": "Preop creatinine",

    "preop_hb": "Preop hemoglobin",

    "preop_hct": "Preop hematocrit",

    "preop_wbc": "Preop white blood cells",



    "intraop_mean_ebl": "Mean blood loss",

    "intraop_max_ebl": "Maximum blood loss",

    "intraop_delta_ebl": "Change in blood loss",



    "intraop_mean_psa": "Mean plasma solution",

    "intraop_max_psa": "Maximum plasma solution",

    "intraop_delta_psa": "Change in plasma solution",



    "diag_neoplasms": "Neoplasm diagnosis",

    "diag_eyeear": "Eye and ear disorder",

    "diag_circulatory": "Circulatory disorder",

    "diag_digestive": "Digestive disorder",

    "diag_respiratory": "Respiratory disorder",

    "diag_endocrine": "Endocrine disorder",

    "diag_genitourinary": "Genitourinary disorder",



    "preop_med_a02": "Preop acid-related medication",

    "preop_med_a06": "Preop laxative use",

    "preop_med_j01": "Preop systemic antibiotic",

    "preop_med_nan": "Preop medication category missing",

    "preop_med_missing": "Preop medication category missing",

    "preop_med_unknown": "Preop medication category missing",

}



SPECIAL_UPPER = {

    "hr", "rr", "spo2", "fio2", "uo", "dbp", "mbp", "sbp",

    "bp", "vt", "pip", "peep", "pplat", "pmean", "hct", "hb",

    "nibp", "abp", "etco2", "alp", "ast", "alt", "cci",

}



CLINICAL_TERM_MAP = {

    "ebl": "blood loss",

    "psa": "plasma solution",

    "platelet": "platelets",

    "lymphocyte": "lymphocytes",

    "alp": "alkaline phosphatase",

    "hb": "hemoglobin",

    "hct": "hematocrit",

    "wbc": "white blood cells",

}



DIAGNOSIS_TERM_MAP = {

    "eyeear": "Eye and ear disorder",

    "neoplasms": "Neoplasm diagnosis",

    "circulatory": "Circulatory disorder",

    "digestive": "Digestive disorder",

    "respiratory": "Respiratory disorder",

    "endocrine": "Endocrine disorder",

    "genitourinary": "Genitourinary disorder",

    "musculoskeletal": "Musculoskeletal disorder",

    "infectious": "Infectious disease",

}





def pretty_feature_name(name: str) -> str:

    n = str(name)

    n = re.sub(r"^(num|cat)__", "", n)



    is_missing = n.startswith("missingindicator_")

    if is_missing:

        n = n[len("missingindicator_"):]



    mapped = SHORT_LABEL_MAP.get(n.lower())

    if mapped is not None:

        return f"Missing: {mapped}" if is_missing else mapped



    if n.lower().startswith("int_"):

        label = (

            n[4:]

            .replace("_x_", " × ")

            .replace("_", " ")

            .lower()

        )

        label = label[0].upper() + label[1:] if label else "Interaction"

        label = label.replace(" or ", " OR ")

        return f"Missing: {label}" if is_missing else label



    if n.upper().startswith("DIAG_"):

        core = n[5:].strip("_")

        label = DIAGNOSIS_TERM_MAP.get(

            core.lower(),

            core.replace("_", " ").capitalize() + " disorder",

        )

        return f"Missing: {label}" if is_missing else label



    if n.upper().startswith("CCI_"):

        core = n[4:].replace("_", " ").strip()

        label = f"CCI: {core.capitalize()}"

        return f"Missing: {label}" if is_missing else compress_words(label)



    if n.upper().startswith("PROC_"):

        core = n[5:].replace("_", " ").strip()

        label = f"Procedure: {core.capitalize()}"

        return f"Missing: {label}" if is_missing else compress_words(label)



    if n.lower().startswith("preop_med_"):

        core = n[len("preop_med_"):].strip("_")

        medication_map = {

            "a02": "Preop acid-related medication",

            "a06": "Preop laxative use",

            "j01": "Preop systemic antibiotic",

        }



        if core.lower() in {"nan", "na", "none", "missing", "unknown"}:

            label = "Preop medication category missing"

        elif core.lower() in medication_map:

            label = medication_map[core.lower()]

        else:

            label = f"Preop medication {core.upper()}"



        return f"Missing: {label}" if is_missing else compress_words(label)



    phase = ""

    for prefix, phase_name in [

        ("preop_", "Preop "),

        ("postop_", "Postop "),

        ("intraop_", ""),

    ]:

        if n.lower().startswith(prefix):

            phase = phase_name

            n = n[len(prefix):]

            break



    metric = ""

    if n.lower().startswith("mean_abs_delta_"):

        metric = "Mean change in "

        n = n[len("mean_abs_delta_"):]

    else:

        match = re.match(

            r"^(mean|min|max|std|range|auc|trend|delta|median)_",

            n,

            flags=re.IGNORECASE,

        )



        if match:

            key = match.group(1).lower()

            metric = {

                "mean": "Mean ",

                "min": "Minimum ",

                "max": "Maximum ",

                "std": "Variability in ",

                "range": "Range of ",

                "auc": "Cumulative ",

                "trend": "Trend in ",

                "delta": "Change in ",

                "median": "Median ",

            }[key]

            n = n[len(match.group(1)) + 1:]



    clinical_term = CLINICAL_TERM_MAP.get(n.lower())



    if clinical_term is not None:

        label = (

            metric + clinical_term

            if metric

            else phase + clinical_term

        )

    else:

        tokens: List[str] = []



        for token in n.split("_"):

            lower = token.lower()



            if lower in CLINICAL_TERM_MAP:

                tokens.append(CLINICAL_TERM_MAP[lower])



            elif lower in SPECIAL_UPPER:

                formatted = lower.upper()

                formatted = formatted.replace("SPO2", "SpO₂")

                formatted = formatted.replace("FIO2", "FiO₂")

                formatted = formatted.replace("ETCO2", "EtCO₂")

                tokens.append(formatted)



            elif len(token) <= 3:

                tokens.append(token.upper())



            else:

                tokens.append(token.lower())



        core = " ".join(tokens).strip()

        label = metric + core if metric else phase + core



    label = label.strip()



    if label:

        label = label[0].upper() + label[1:]



    if is_missing:

        label = "Missing: " + label



    return compress_words(label)





# =============================================================================

# CURRENT STRICT-OOF COHORT RECONSTRUCTION

# =============================================================================



def reconstruct_current_run(

    module,

    run_dir: pathlib.Path,

    data_path: pathlib.Path,

) -> Dict[str, Any]:

    config = load_json(run_dir / "config.json")



    configured_data_path = pathlib.Path(

        str(config.get("data_path", data_path))

    )



    if (

        data_path == DEFAULT_DATA_PATH

        and configured_data_path.exists()

    ):

        data_path = configured_data_path



    print("\n" + "=" * 100)

    print("RECONSTRUCTING STRICT-OOF COHORT AND SAVED TEST ORDER")

    print("=" * 100)



    source = pd.read_csv(

        require_file(data_path),

        low_memory=False,

    )



    cohort, cohort_flow = module.apply_reviewer_cohort_exclusions(

        source,

        target_column=str(

            config.get("target_column", "mortality_30d")

        ),

        exclude_asa6=bool(

            config.get("exclude_asa6", True)

        ),

    )



    if bool(config.get("add_interactions", True)):

        cohort = module.add_mortality_interactions(cohort)


    X_raw = module.extract_model_features_classification(

        cohort,

        verbose=False,

    )



    target_column = str(

        config.get("target_column", "mortality_30d")

    )



    y_all = (

        cohort.loc[X_raw.index, target_column]

        .astype(int)

        .to_numpy()

    )



    X_raw = module.clean_raw_predictors(X_raw)



    test_predictions = pd.read_csv(

        require_file(

            run_dir / "test_predictions_all_models.csv"

        )

    )



    required_columns = {

        "final_cohort_row_position",

        "source_row_position",

        "y_true",

    }



    missing = required_columns - set(test_predictions.columns)



    if missing:

        raise KeyError(

            "test_predictions_all_models.csv lacks columns: "

            f"{sorted(missing)}"

        )



    test_positions = (

        test_predictions["final_cohort_row_position"]

        .astype(int)

        .to_numpy()

    )



    X_test_raw = (

        X_raw.iloc[test_positions]

        .reset_index(drop=True)

    )



    y_test = y_all[test_positions]



    if not np.array_equal(

        y_test,

        test_predictions["y_true"].astype(int).to_numpy(),

    ):

        raise RuntimeError(

            "Reconstructed outcomes do not match the saved test predictions."

        )



    print(cohort_flow.to_string(index=False))

    print(f"Test encounters: {len(y_test):,}")

    print(f"Test deaths:     {int(y_test.sum()):,}")

    print(f"Raw predictors:  {X_raw.shape[1]:,}")



    return {

        "config": config,

        "data_path": data_path,

        "X_test_raw": X_test_raw,

        "y_test": y_test,

        "test_predictions": test_predictions,

    }





# =============================================================================

# FOLD-SPECIFIC TRANSFORMED TEST MATRIX ALIGNMENT

# =============================================================================



def transformed_matrix_for_fold(

    raw_frame: pd.DataFrame,

    preprocessor,

    variance_selector,

    selected_indices: np.ndarray,

) -> np.ndarray:

    matrix = preprocessor.transform(raw_frame)



    matrix = np.nan_to_num(

        matrix,

        nan=0.0,

        posinf=0.0,

        neginf=0.0,

    ).astype(np.float32)



    matrix = variance_selector.transform(

        matrix

    ).astype(np.float32)



    return matrix[:, selected_indices].astype(np.float32)





def feature_domain_map_from_metadata(

    feature_names: np.ndarray,

    metadata: Mapping[str, Any],

) -> Dict[str, str]:

    output: Dict[str, str] = {}



    for domain, indices in metadata.get(

        "domain_indices",

        {},

    ).items():

        for index in indices:

            index = int(index)



            if 0 <= index < len(feature_names):

                output[str(feature_names[index])] = canonical_domain(domain)



    return output





def reconstruct_union_test_matrix(

    reconstructed: Mapping[str, Any],

    run_dir: pathlib.Path,

    cache_path: pathlib.Path,

    *,

    force_recompute: bool,

) -> Dict[str, Any]:

    if cache_path.exists() and not force_recompute:

        print("\nLoading cached strict-OOF aligned test-set matrix:", cache_path)



        cached = np.load(

            cache_path,

            allow_pickle=True,

        )



        required_cache_keys = {

            "features",

            "domains",

            "values",

            "fold_presence_count",

            "test_n",

            "run_id",

        }

        missing_cache_keys = required_cache_keys - set(cached.files)

        if missing_cache_keys:

            raise RuntimeError(

                "The aligned-matrix cache lacks strict-OOF provenance keys: "

                f"{sorted(missing_cache_keys)}. Re-run with "

                "--force_recompute_matrix."

            )



        cached_test_n = int(

            np.asarray(cached["test_n"]).reshape(-1)[0]

        )

        cached_run_id = str(

            np.asarray(cached["run_id"], dtype=object).reshape(-1)[0]

        )



        if cached_test_n != len(reconstructed["X_test_raw"]):

            raise RuntimeError(

                "The aligned-matrix cache has a different test-set size. "

                "Re-run with --force_recompute_matrix."

            )



        if cached_run_id != run_dir.name:

            raise RuntimeError(

                "The aligned-matrix cache belongs to a different run "

                f"({cached_run_id} versus {run_dir.name}). Re-run with "

                "--force_recompute_matrix."

            )



        return {

            "features": normalize_object_array(cached["features"]),

            "domains": normalize_object_array(cached["domains"]),

            "values": cached["values"].astype(np.float32),

            "fold_presence_count": cached[

                "fold_presence_count"

            ].astype(int),

        }



    config = reconstructed["config"]

    X_test_raw = reconstructed["X_test_raw"]

    n_folds = int(config.get("n_folds", 5))



    fold_metadata: List[Dict[str, Any]] = []

    union_feature_set = set()

    domain_votes: Dict[str, Counter] = defaultdict(Counter)



    print("\n" + "=" * 100)

    print("ALIGNING FOLD-SPECIFIC TRANSFORMED HOLDOUT MATRICES")

    print("=" * 100)



    for fold_number in range(1, n_folds + 1):

        fold_dir = (

            run_dir

            / "fold_artifacts"

            / f"fold_{fold_number}"

        )



        selected_names = normalize_object_array(

            np.load(

                require_file(

                    fold_dir / "selected_feature_names.npy"

                ),

                allow_pickle=True,

            )

        )



        metadata = load_json(

            fold_dir / "selected_domain_metadata.json"

        )



        feature_domains = feature_domain_map_from_metadata(

            selected_names,

            metadata,

        )



        for feature in selected_names:

            union_feature_set.add(str(feature))



        for feature, domain in feature_domains.items():

            domain_votes[feature][domain] += 1



        fold_metadata.append(

            {

                "fold_number": fold_number,

                "fold_dir": fold_dir,

                "selected_names": selected_names,

            }

        )



    union_features = np.asarray(

        sorted(union_feature_set),

        dtype=object,

    )



    feature_to_union = {

        str(feature): index

        for index, feature in enumerate(union_features)

    }



    n_test = len(X_test_raw)

    n_union = len(union_features)



    value_sum = np.zeros(

        (n_test, n_union),

        dtype=np.float32,

    )

    fold_presence_count = np.zeros(

        n_union,

        dtype=np.int16,

    )



    for metadata in fold_metadata:

        fold_number = metadata["fold_number"]

        fold_dir = metadata["fold_dir"]

        selected_names = metadata["selected_names"]



        print(

            f"Transforming fold {fold_number}/{n_folds}: "

            f"{len(selected_names):,} features"

        )



        preprocessor = joblib.load(

            require_file(

                fold_dir / "preprocessor.joblib"

            )

        )



        variance_selector = joblib.load(

            require_file(

                fold_dir / "variance_selector.joblib"

            )

        )



        selected_indices = np.load(

            require_file(

                fold_dir / "selected_original_indices.npy"

            )

        ).astype(int)



        fold_values = transformed_matrix_for_fold(

            X_test_raw,

            preprocessor,

            variance_selector,

            selected_indices,

        )



        if fold_values.shape[1] != len(selected_names):

            raise RuntimeError(

                f"Fold {fold_number} transformed feature count does not "

                "match selected_feature_names.npy."

            )



        union_indices = np.asarray(

            [

                feature_to_union[str(feature)]

                for feature in selected_names

            ],

            dtype=int,

        )



        value_sum[:, union_indices] += fold_values

        fold_presence_count[union_indices] += 1



        del fold_values



    divisor = np.maximum(

        fold_presence_count.astype(np.float32),

        1.0,

    )



    union_values = value_sum / divisor[np.newaxis, :]



    final_domains: List[str] = []



    for feature in union_features:

        votes = domain_votes.get(str(feature), Counter())



        final_domains.append(

            votes.most_common(1)[0][0]

            if votes

            else "Other"

        )



    result = {

        "features": union_features,

        "domains": np.asarray(

            final_domains,

            dtype=object,

        ),

        "values": union_values,

        "fold_presence_count": fold_presence_count,

    }



    np.savez_compressed(

        cache_path,

        features=result["features"],

        domains=result["domains"],

        values=result["values"],

        fold_presence_count=result["fold_presence_count"],

        test_n=np.asarray(

            [len(X_test_raw)],

            dtype=np.int64,

        ),

        run_id=np.asarray(

            [run_dir.name],

            dtype=object,

        ),

    )



    print("Saved aligned test-matrix cache:", cache_path)

    print(f"Union transformed features: {n_union:,}")



    return result





# =============================================================================

# CURRENT DIRECT DARN IMPORTANCE TABLE

# =============================================================================



def discover_importance_file(
    run_dir: pathlib.Path,
) -> pathlib.Path:
    """
    Locate the Uniform DARN GradientSHAP importance table generated from the
    same final temporal-safe strict-OOF run.
    """
    return require_file(
        run_dir
        / "figures_revised_manuscript"
        / "figure4_darn_xgboost_AB_strict_oof"
        / "uniform_darn_gradientshap_feature_importance.csv"
    )



def load_importance_table(

    path: pathlib.Path,

) -> pd.DataFrame:

    table = pd.read_csv(require_file(path))



    required = {

        "feature",

        "domain",

        "mean_absolute_direct_attribution",

    }



    missing = required - set(table.columns)



    if missing:

        raise KeyError(

            f"{path.name} is missing columns: {sorted(missing)}"

        )



    table = table.copy()



    table["feature"] = table["feature"].astype(str)

    table["domain"] = table["domain"].map(canonical_domain)



    table["mean_absolute_direct_attribution"] = pd.to_numeric(

        table["mean_absolute_direct_attribution"],

        errors="coerce",

    ).fillna(0.0)



    if "pretty_feature" not in table.columns:

        table["pretty_feature"] = table["feature"].map(

            pretty_feature_name

        )

    else:

        # Recreate labels so this script always uses the current tidy labels.

        table["pretty_feature"] = table["feature"].map(

            pretty_feature_name

        )



    return table.sort_values(

        "mean_absolute_direct_attribution",

        ascending=False,

    ).reset_index(drop=True)





# =============================================================================

# ANALYSIS TABLES

# =============================================================================



def build_analysis_tables(

    union_matrix: Mapping[str, Any],

    importance_table: pd.DataFrame,

    *,

    top_k: int,

) -> Dict[str, Any]:

    features = union_matrix["features"].astype(str)

    domains = union_matrix["domains"].astype(str)

    values = union_matrix["values"].astype(np.float64)



    feature_to_index = {

        feature: index

        for index, feature in enumerate(features)

    }



    available_importance = importance_table[

        importance_table["feature"].isin(feature_to_index)

    ].copy()



    if available_importance.empty:

        raise RuntimeError(

            "None of the strict-OOF attributed features were present in "

            "the aligned transformed test-set matrix."

        )



    duplicated_labels = (

        available_importance["pretty_feature"]

        .astype(str)

        .duplicated(keep=False)

    )

    if duplicated_labels.any():

        duplicate_table = available_importance.loc[

            duplicated_labels,

            ["feature", "pretty_feature"],

        ]

        print(

            "Warning: duplicate display labels remain after feature-label "

            "normalization:\n"

            + duplicate_table.to_string(index=False)

        )



    if len(available_importance) < top_k:

        print(

            f"Warning: only {len(available_importance)} attributed features "

            f"were present in the aligned test matrix."

        )



    top_table = available_importance.head(top_k).copy()



    top_indices = np.asarray(

        [

            feature_to_index[feature]

            for feature in top_table["feature"]

        ],

        dtype=int,

    )



    X_top = pd.DataFrame(

        values[:, top_indices],

        columns=top_table["feature"],

    )



    feature_correlation = X_top.corr(

        method="spearman"

    ).fillna(0.0)



    np.fill_diagonal(

        feature_correlation.values,

        1.0,

    )



    distance = (

        1.0

        - np.abs(

            feature_correlation.to_numpy(

                dtype=float

            )

        )

    )



    distance = np.clip(

        distance,

        0.0,

        2.0,

    )


    distance = (

        distance

        + distance.T

    ) / 2.0



    np.fill_diagonal(

        distance,

        0.0,

    )



    condensed = squareform(

        distance,

        checks=False,

    )



    feature_linkage = linkage(

        condensed,

        method=CLUSTER_LINKAGE_METHOD,

    )



    leaf_order = dendrogram(

        feature_linkage,

        no_plot=True,

    )["leaves"]



    ordered_features = [

        top_table.iloc[index]["feature"]

        for index in leaf_order

    ]



    ordered_labels = [

        pretty_feature_name(feature)

        for feature in ordered_features

    ]



    ordered_correlation = feature_correlation.loc[

        ordered_features,

        ordered_features,

    ]



    # Domain-level input summaries are formed by z-scoring each selected

    # transformed feature across the full held-out test set and averaging the

    # standardized values within each domain.

    feature_mean = np.nanmean(

        values,

        axis=0,

    )



    feature_sd = np.nanstd(

        values,

        axis=0,

    )



    feature_sd = np.where(

        feature_sd <= 1e-12,

        1.0,

        feature_sd,

    )



    values_z = (

        values - feature_mean

    ) / feature_sd



    domain_summary: Dict[str, np.ndarray] = {}



    for domain in sorted(set(domains)):

        indices = np.where(

            domains == domain

        )[0]



        if len(indices) == 0:

            continue



        domain_summary[domain] = np.nanmean(

            values_z[:, indices],

            axis=1,

        )



    domain_summary_df = pd.DataFrame(

        domain_summary

    )



    domain_correlation = domain_summary_df.corr(

        method="spearman"

    ).fillna(0.0)



    np.fill_diagonal(

        domain_correlation.values,

        1.0,

    )



    domain_attribution = (

        importance_table.groupby(

            "domain",

            as_index=False,

        )

        .agg(

            n_union_features=(

                "feature",

                "size",

            ),

            summed_mean_absolute_attribution=(

                "mean_absolute_direct_attribution",

                "sum",

            ),

        )

    )



    total = float(

        domain_attribution[

            "summed_mean_absolute_attribution"

        ].sum()

    )



    if total <= 0:

        raise ValueError(

            "Total Uniform DARN attribution is zero."

        )



    domain_attribution[

        "direct_attribution_percent"

    ] = (

        domain_attribution[

            "summed_mean_absolute_attribution"

        ]

        / total

        * 100.0

    )



    domain_attribution[

        "display_domain"

    ] = domain_attribution[

        "domain"

    ].map(display_domain)



    domain_attribution = domain_attribution.sort_values(

        "direct_attribution_percent",

        ascending=True,

    ).reset_index(drop=True)



    return {

        "top_table": top_table,

        "ordered_features": ordered_features,

        "ordered_labels": ordered_labels,

        "ordered_correlation": ordered_correlation,

        "feature_linkage": feature_linkage,

        "domain_correlation": domain_correlation,

        "domain_attribution": domain_attribution,

    }





# =============================================================================

# FIGURE

# =============================================================================



def configure_style() -> None:
    """Use enlarged publication typography consistent with the final figures."""
    mpl.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 13,
            "axes.linewidth": 1.0,
            "axes.edgecolor": "black",
            "axes.titlesize": 15,
            "axes.labelsize": 14,
            "xtick.labelsize": 12.5,
            "ytick.labelsize": 12.5,
            "legend.fontsize": 12,
            "legend.frameon": False,
            "figure.titlesize": 19,
            "figure.facecolor": "white",
            "savefig.facecolor": "white",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )



def save_figure_all_formats(

    fig: plt.Figure,

    png_path: pathlib.Path,

) -> None:

    fig.savefig(

        png_path,

        dpi=600,

        bbox_inches="tight",

    )

    fig.savefig(

        png_path.with_suffix(".pdf"),

        bbox_inches="tight",

    )

    fig.savefig(

        png_path.with_suffix(".svg"),

        bbox_inches="tight",

    )



    try:

        fig.savefig(

            png_path.with_suffix(".tiff"),

            dpi=600,

            bbox_inches="tight",

            pil_kwargs={"compression": "tiff_lzw"},

        )

    except Exception as exc:

        print("TIFF export skipped:", exc)





def create_figure(

    reconstructed: Mapping[str, Any],

    analysis: Mapping[str, Any],

    output_dir: pathlib.Path,

) -> pathlib.Path:

    configure_style()



    correlation_cmap = cm.get_cmap(

        CORRELATION_CMAP

    )



    attribution_cmap = cm.get_cmap(

        ATTRIBUTION_CMAP

    )



    ordered_correlation = analysis[

        "ordered_correlation"

    ]



    ordered_labels = analysis[

        "ordered_labels"

    ]



    feature_linkage = analysis[

        "feature_linkage"

    ]



    top_table = analysis[

        "top_table"

    ]



    domain_correlation = analysis[

        "domain_correlation"

    ]



    domain_attribution = analysis[

        "domain_attribution"

    ]



    fig, axes = plt.subplots(

        2,

        2,

        figsize=(25, 22),

    )



    (

        (ax_a, ax_b),

        (ax_c, ax_d),

    ) = axes



    fig.suptitle(

        "Feature correlation and domain structure of the Uniform DARN component",

        fontsize=19,

        fontweight="bold",

        y=0.982,

    )



    # Test-set size and feature-ranking provenance are reported in the caption.

    # -------------------------------------------------------------------------

    # Panel A

    # -------------------------------------------------------------------------

    matrix_a = ordered_correlation.to_numpy(

        dtype=float

    )



    image_a = ax_a.imshow(

        matrix_a,

        cmap=correlation_cmap,

        vmin=-1,

        vmax=1,

        aspect="auto",

        interpolation="nearest",

    )



    ax_a.set_xticks(

        np.arange(len(ordered_labels))

    )

    ax_a.set_yticks(

        np.arange(len(ordered_labels))

    )



    ax_a.set_xticklabels(

        ordered_labels,

        rotation=90,

        ha="center",

        fontsize=10.5,

    )

    ax_a.set_yticklabels(

        ordered_labels,

        fontsize=10.5,

    )



    ax_a.set_title(

        "A. Correlation among top attributed features",

        fontweight="bold",

        loc="left",

        pad=10,

    )

    ax_a.set_xlabel(

        "Top direct-attribution features"

    )

    ax_a.set_ylabel(

        "Top direct-attribution features"

    )



    colorbar_a = fig.colorbar(

        image_a,

        ax=ax_a,

        fraction=0.046,

        pad=0.025,

    )

    colorbar_a.set_label(

        "Spearman correlation"

    )



    # -------------------------------------------------------------------------

    # Panel B

    # -------------------------------------------------------------------------

    dendrogram(

        feature_linkage,

        labels=[

            pretty_feature_name(feature)

            for feature in top_table["feature"]

        ],

        orientation="right",

        leaf_font_size=10.5,

        ax=ax_b,

        color_threshold=(

            0.70

            * float(

                np.max(

                    feature_linkage[:, 2]

                )

            )

        ),

        above_threshold_color="dimgray",

    )



    ax_b.set_title(

        "B. Horizontal hierarchical clustering of top attributed features",

        fontweight="bold",

        loc="left",

        pad=10,

    )

    ax_b.set_xlabel(

        "Correlation distance: 1 − |Spearman ρ|"

    )

    ax_b.set_ylabel(

        "Top direct-attribution features"

    )

    ax_b.grid(

        axis="x",

        linestyle="--",

        alpha=0.20,

    )



    # -------------------------------------------------------------------------

    # Panel C

    # -------------------------------------------------------------------------

    domain_names = domain_correlation.columns.tolist()

    domain_labels = [

        display_domain(domain)

        for domain in domain_names

    ]



    matrix_c = domain_correlation.to_numpy(

        dtype=float

    )



    image_c = ax_c.imshow(

        matrix_c,

        cmap=correlation_cmap,

        vmin=-1,

        vmax=1,

        aspect="equal",

        interpolation="nearest",

    )



    ax_c.set_xticks(

        np.arange(len(domain_names))

    )

    ax_c.set_yticks(

        np.arange(len(domain_names))

    )



    ax_c.set_xticklabels(

        domain_labels,

        rotation=38,

        ha="right",

        fontsize=12.0,

    )

    ax_c.set_yticklabels(

        domain_labels,

        fontsize=12.0,

    )



    for row_index in range(len(domain_names)):

        for column_index in range(len(domain_names)):

            value = float(

                matrix_c[

                    row_index,

                    column_index,

                ]

            )



            ax_c.text(

                column_index,

                row_index,

                f"{value:.2f}",

                ha="center",

                va="center",

                fontsize=10.5,

                color=(

                    "white"

                    if abs(value) >= 0.55

                    else "black"

                ),

            )



    ax_c.set_title(

        "C. Correlation among clinical domains",

        fontweight="bold",

        loc="left",

        pad=10,

    )

    ax_c.set_xlabel(

        "Clinical input domain"

    )

    ax_c.set_ylabel(

        "Clinical input domain"

    )



    colorbar_c = fig.colorbar(

        image_c,

        ax=ax_c,

        fraction=0.046,

        pad=0.025,

    )

    colorbar_c.set_label(

        "Spearman correlation"

    )



    # -------------------------------------------------------------------------

    # Panel D

    # -------------------------------------------------------------------------

    y_positions = np.arange(

        len(domain_attribution)

    )



    domain_colors = [

        attribution_cmap(value)

        for value in np.linspace(

            0.10,

            0.92,

            len(domain_attribution),

        )

    ]



    bars_d = ax_d.barh(

        y_positions,

        domain_attribution[

            "direct_attribution_percent"

        ],

        color=domain_colors,

        edgecolor="none",

    )



    ax_d.set_yticks(y_positions)

    ax_d.set_yticklabels(

        domain_attribution["display_domain"],

        fontsize=12.5,

    )



    ax_d.set_xlabel(

        "Share of total absolute GradientSHAP attribution (%)"

    )

    ax_d.set_title(

        "D. Direct domain attribution for Uniform DARN",

        fontweight="bold",

        loc="left",

        pad=10,

    )

    ax_d.grid(

        axis="x",

        linestyle="--",

        alpha=0.24,

    )



    maximum = max(

        float(

            domain_attribution[

                "direct_attribution_percent"

            ].max()

        ),

        1e-9,

    )



    ax_d.set_xlim(

        0,

        maximum * 1.24,

    )



    for bar, row in zip(

        bars_d,
        domain_attribution.itertuples(),

    ):

        ax_d.text(

            bar.get_width() + maximum * 0.016,

            bar.get_y() + bar.get_height() / 2,

            (

                f"{row.direct_attribution_percent:.1f}% "

                f"(n={int(row.n_union_features)})"

            ),

            va="center",

            ha="left",

            fontsize=11.5,

        )



    # Attribution interpretation is reported in the figure caption.

    fig.tight_layout(

        rect=(0.025, 0.030, 0.99, 0.955),

        h_pad=3.4,

        w_pad=3.4,

    )



    output_path = (

        output_dir

        / f"{FIGURE_BASENAME}.png"

    )



    save_figure_all_formats(

        fig,

        output_path,

    )



    plt.show()

    plt.close(fig)



    return output_path





# =============================================================================

# MAIN WORKFLOW

# =============================================================================



def run_analysis(

    run_dir: pathlib.Path,

    pipeline_module_path: pathlib.Path,

    data_path: pathlib.Path,

    output_dir: pathlib.Path,

    *,

    top_k: int,

    force_recompute_matrix: bool,

) -> None:

    output_dir.mkdir(

        parents=True,

        exist_ok=True,

    )



    print("=" * 100)

    print("FINAL TEMPORAL-SAFE STRICT-OOF SUPPLEMENTARY XAI CORRELATION")

    print("=" * 100)

    print("Run directory   :", run_dir)

    print("Pipeline module :", pipeline_module_path)

    print("Output directory:", output_dir)



    pipeline = load_pipeline_module(

        pipeline_module_path

    )



    reconstructed = reconstruct_current_run(

        pipeline,

        run_dir,

        data_path,

    )



    matrix_cache = (

        output_dir

        / "strict_oof_aligned_union_test_matrix.npz"

    )



    union_matrix = reconstruct_union_test_matrix(

        reconstructed,

        run_dir,

        matrix_cache,

        force_recompute=force_recompute_matrix,

    )



    importance_file = discover_importance_file(

        run_dir

    )



    importance_table = load_importance_table(

        importance_file

    )



    analysis = build_analysis_tables(

        union_matrix,

        importance_table,

        top_k=top_k,

    )



    # Save numerical tables.

    analysis["top_table"].to_csv(

        output_dir

        / "top_direct_DARN_features_used_for_correlation.csv",

        index=False,

    )



    analysis["ordered_correlation"].to_csv(

        output_dir

        / "top_direct_DARN_features_Spearman_correlation.csv"

    )



    pd.DataFrame(

        {

            "cluster_order": np.arange(

                1,

                len(analysis["ordered_features"]) + 1,

            ),

            "feature": analysis["ordered_features"],

            "pretty_feature": analysis["ordered_labels"],

        }

    ).to_csv(

        output_dir

        / "top_direct_DARN_feature_cluster_order.csv",

        index=False,

    )



    analysis["domain_correlation"].to_csv(

        output_dir

        / "domain_input_summary_Spearman_correlation.csv"

    )



    analysis["domain_attribution"].to_csv(

        output_dir

        / "direct_DARN_domain_attribution_share.csv",

        index=False,

    )



    main_figure = create_figure(

        reconstructed,

        analysis,

        output_dir,

    )



    summary = {

        "analysis_version": "strict-OOF",

        "run_id": run_dir.name,

        "run_directory": str(run_dir),

        "pipeline_module": str(pipeline_module_path),

        "data_path": str(reconstructed["data_path"]),

        "importance_file": str(importance_file),

        "matrix_cache": str(matrix_cache),

        "cache_is_run_scoped": True,

        "test_n": int(

            len(reconstructed["y_test"])

        ),

        "test_deaths": int(

            reconstructed["y_test"].sum()

        ),

        "n_union_transformed_features": int(

            len(union_matrix["features"])

        ),

        "top_k": int(

            len(analysis["top_table"])

        ),

        "feature_clustering_distance": (

            "1 - absolute Spearman correlation"

        ),

        "feature_clustering_linkage": (

            CLUSTER_LINKAGE_METHOD

        ),

        "domain_summary_definition": (

            "Mean of test-set-standardized aligned transformed features "

            "within each clinical domain"

        ),

        "domain_attribution_definition": (

            "Share of summed mean absolute direct Uniform DARN "

            "GradientSHAP attribution"

        ),

        "correlation_population": (

            "Complete locked strict-OOF held-out test cohort"

        ),

        "main_figure": str(main_figure),

        "interpretation_note": (

            "Spearman correlations and hierarchical clustering describe "

            "dependence among transformed model inputs in the held-out test "

            "strict-OOF held-out test cohort. They do not establish causal "

            "relationships, feature substitutability, or domain necessity."

        ),

    }



    save_json(

        summary,

        output_dir

        / "FigS_TemporalSafe_StrictOOF_XAI_Input_Correlation_summary.json",

    )



    print("\n" + "=" * 100)

    print("FINAL TEMPORAL-SAFE STRICT-OOF XAI CORRELATION FIGURE COMPLETE")

    print("=" * 100)

    print("Main figure:", main_figure)

    print("Output directory:", output_dir)



    print("\nTop direct Uniform DARN features:")

    print(

        analysis["top_table"][

            [

                "rank",

                "pretty_feature",

                "domain",

                "mean_absolute_direct_attribution",

                "fold_presence_count",

            ]

        ]

        .head(top_k)

        .to_string(index=False)

    )



    print("\nDirect Uniform DARN domain attribution:")

    print(

        analysis["domain_attribution"][

            [

                "display_domain",

                "n_union_features",

                "direct_attribution_percent",

            ]

        ]

        .sort_values(

            "direct_attribution_percent",

            ascending=False,

        )

        .to_string(index=False)

    )





# =============================================================================

# JUPYTER-SAFE ARGUMENT PARSING

# =============================================================================



def parse_args(

    argv: Optional[Sequence[str]] = None,

) -> argparse.Namespace:

    parser = argparse.ArgumentParser(

        allow_abbrev=False,

        description=(

            "Create the final temporal-safe strict-OOF supplementary XAI input "

            "correlation and clustering figure."

        ),

    )



    parser.add_argument(

        "--run_dir",

        type=pathlib.Path,

        default=DEFAULT_RUN_DIR,

    )



    parser.add_argument(

        "--pipeline_module",

        type=pathlib.Path,

        default=DEFAULT_PIPELINE_MODULE,

    )



    parser.add_argument(

        "--data_path",

        type=pathlib.Path,

        default=DEFAULT_DATA_PATH,

    )



    parser.add_argument(

        "--output_dir",

        type=pathlib.Path,

        default=None,

    )



    parser.add_argument(

        "--top_k",

        type=int,

        default=TOP_K,

    )



    parser.add_argument(

        "--force_recompute_matrix",

        action="store_true",

        help=(

            "Recompute the fold-aligned transformed test-set matrix instead "

            "of loading the saved cache."

        ),

    )



    raw_arguments = list(

        sys.argv[1:]

        if argv is None

        else argv

    )



    filtered_arguments: List[str] = []

    skip_next = False



    for argument in raw_arguments:

        if skip_next:

            skip_next = False

            continue



        if argument in {"-f", "--f"}:

            skip_next = True

            continue



        if (

            argument.startswith("-f=")

            or argument.startswith("--f=")

        ):

            continue



        filtered_arguments.append(argument)



    args, unknown = parser.parse_known_args(

        filtered_arguments

    )



    if unknown:

        print(

            "Ignoring unrecognized Jupyter/IPython arguments:",

            " ".join(map(str, unknown)),

        )



    return args





def main() -> None:

    args = parse_args()



    output_dir = (

        args.output_dir

        if args.output_dir is not None

        else args.run_dir / DEFAULT_OUTPUT_SUBDIR

    )



    run_analysis(

        run_dir=args.run_dir,

        pipeline_module_path=args.pipeline_module,

        data_path=args.data_path,

        output_dir=output_dir,

        top_k=args.top_k,

        force_recompute_matrix=args.force_recompute_matrix,

    )





if __name__ == "__main__":

    main()